### ISSUE TITLE
alt+enter doesn't add a new line in the commit body on macOS

### ISSUE THREAD

**Issue by Crocmagnon** [stefanlogue/meteor#14]
### 🐛 Describe the bug

alt+Enter doesn't add a new line in the commit body.

### Versions

meteor : dev (installed on 2024-01-21 with `go install github.com/stefanlogue/meteor@latest`)
fish : 3.7.0
iTerm2 : 3.4.22
macOS : 14.2

**Comment by stefanlogue** [comment]
Seems to work for me with kitty 0.31.0, tmux3.3a, macOS 14.2. (Option+Enter works, although ctrl+j doesn't seem to work). Could this be iTerm2 masking some keys?

**Comment by stefanlogue** [comment]
I've just remembered I've got `ctrl+j` remapped in tmux, so it wouldn't work for me anyway. Checked outside of tmux and seems to work fine.

**Comment by Crocmagnon** [comment]
`ctrl+j` works fine in iTerm. I tried in the default Terminal app and got the same behavior as in iTerm.
I forgot to mention that I'm using a French AZERTY layout. Switching to US QWERTY didn't change the behavior.
I searched through iTerm's key mappings but didn't find anything set to `option+enter`.

**Comment by mikelorant** [comment]
For iTerm2 you need to do select the following option.

![](https://github.com/mikelorant/committed/blob/main/docs/keyboard-options-iterm2.png?raw=true)

**Comment by Crocmagnon** [comment]
Indeed. To give more context, here's where this option lives:

![Screenshot 2024-02-01 at 09 12 10](https://github.com/stefanlogue/meteor/assets/3630554/ff299421-649d-48ce-b90c-46f8a40eb884)

**Comment by stefanlogue** [comment]
Nice! Has this solved the issue?

**Comment by Crocmagnon** [comment]
Unfortunately I had to revert back the setting because the option key is used on French AZERTY macOS for some chars such as square brackets (`[ ]`) and setting "Esc+" broke those.

**Comment by stefanlogue** [comment]
Are you able to use one option key as Esc+ and the other as normal? 

I don't think this is within the scope of the tool though, so I'm going to close the issue.

**Comment by Crocmagnon** [comment]
Suggestion: why not changing the shortcut to Shift+Enter? Wouldn't that make the app more accessible accross the board?

**Comment by stefanlogue** [comment]
Sure, I can try and implement this when I get some time this week

**Comment by stefanlogue** [comment]
Ok so it turns out that `shift+enter` is a strange key combination, and most terminal emulators do not follow a standard keycoding for it, with many not supporting it at all. `Option+Enter` does work fine on MacOS, and if `Ctrl+j` is working fine for you then I'd suggest using that going forward.

Alternatively, if you can think of a different key combo which would work better for you, let me know and I'll see what I can do :)
