### ISSUE TITLE
Show the git commit command

### ISSUE THREAD

**Issue by Crocmagnon** [stefanlogue/meteor#15]
### 🚀 The feature, motivation and pitch

Show the git commit command that's generated.

I'm using pre-commit to run checks before committing, and the tool can stop the commit from happening. When using `git commit -m "msg"` directly, I can fix the issues reported, then re-run the last command.
With meteor, I'm forced to go through the wizard again, which is a time loss.

I'd also be happy with a way to re-run the last options, but I guess it would be more difficult to implement.

**Comment by stefanlogue** [comment]
Thanks for the suggestion!

Do you have any ideas on where this would be displayed? I think a logical place would be the final "page", above the prompt for completing the commit

**Comment by Crocmagnon** [comment]
It needs to be displayed after all the prompts disappear, as a standard output ; otherwise if I go through all the screens, don't copy the command, hit enter and pre-commit refuses my commit, I'm good to go all over again.

I'd say either before running the real git commit command, or after detecting it went wrong. E.g. if the return code of the git command is 0 don't display anything but if it's anything else display something like

```
It looks like the commit failed. To run it again without going through meteor's wizard, simply run the following command:
git commit -m "<the message you computed>"
```

**Comment by stefanlogue** [comment]
Sounds good! I'll link this issue once done!

**Comment by Crocmagnon** [comment]
If that’s ok with you I’d like to take a spin at this 🙂

**Comment by stefanlogue** [comment]
Sure thing! Make a fork and a PR when you're ready!
