### ISSUE TITLE
disable the first screen

### ISSUE THREAD

**Issue by Crocmagnon** [stefanlogue/meteor#16]
### 🚀 The feature, motivation and pitch

The first screen with the text describing the tool doesn't add value and gets in the way of committing, it would be nice to have an option to remove it. Maybe show it only the first time the tool is run? Or remove it altogether.

**Comment by stefanlogue** [comment]
For backwards compatibility, I think we could make this a config option. If user has `showIntro` or something similar set to `false`, we skip it
