### ISSUE TITLE
prefix format in documentation is incorrect

### ISSUE THREAD

**Issue by timhatch** [stefanlogue/meteor#19]
### 📚 The doc issue

The example `.meteor.json` given in the docs shows each prefix having two key:value pairs, "title" and "description". e.g.
```
"prefixes": [
  {"title": "feat", "description": a new feature}
]
```
Checking the definition of the `prefix` struct in `config.go` it looks as though the keys should be "type" and "description".

### Suggest a potential alternative/fix

Amend the example `.meteor.json` to follow the struct definition with keys "type" and "description", e.g.
```
"prefixes": [
  {"type": "feat", "description": a new feature}
]
```

**Comment by stefanlogue** [comment]
Good catch! Feel free to make a PR with the amendment, or I can amend it later today

**Comment by timhatch** [comment]
I may get the chance to create a PR later today
