### ISSUE TITLE
Gitmoji

### ISSUE THREAD

**Issue by wfrodriguez** [stefanlogue/meteor#25]
### 🚀 The feature, motivation and pitch

Do you plan to support gitmoji? (https://gitmoji.dev/)

**Comment by stefanlogue** [comment]
I don't think supporting this would be in the scope for the project at the minute, as the main objective of this tool is to help writing [conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/), and Gitmoji isn't part of the spec. 

A lot of CI tools use the conventional commit spec to perform actions based on the commit type, and I don't see how Gitmoji would work in these instances.
