### ISSUE TITLE
Global meteor.json

### ISSUE THREAD

**Issue by gerstorfer** [stefanlogue/meteor#26]
### 🐛 Describe the bug

The config file  `.meteor.json` is not found when placed in `$HOME`. Everything works as expected, when `.meteor.json` is placed above the working dir (even deeply nested) until  the uppermost dir is the home directory. 

It would be nice to have a global configuration in `~/.meteor.json` and/or `~/.config/meteor.json` and/or `~/.config/meteor/meteor.json`

### Versions

meteor version 0.18.0

**Comment by stefanlogue** [comment]
Nice catch! I think I know what's causing the issue and will release a fixed version as soon as I have some time

**Comment by gerstorfer** [comment]
Great! Looking forward to it.

**Comment by sebastianwebber** [comment]
@stefanlogue @gerstorfer i proposed a PR that solves this specific issue.

**Comment by stefanlogue** [comment]
Big thanks to @sebastianwebber for the fix! It's now released in `v0.19`!

**Comment by gerstorfer** [comment]
Thank you @sebastianwebber for the PR and @stefanlogue for releasing the fix so quickly! _Very much_ appreciated
