### ISSUE TITLE
Why assume tickets have 4 digits? This is often not the case

### ISSUE THREAD

**Issue by saulhoward** [stefanlogue/meteor#34]
https://github.com/stefanlogue/meteor/blob/d6a5650bc0f394e29ce23eebb6deaff52ce75e99/git.go#L40

Great project btw! Thanks.

**Comment by stefanlogue** [comment]
I agree, this should probably be `{1,}` instead, matching any number of digits greater than or equal to 1

**Comment by stefanlogue** [comment]
This is now default behaviour in latest release (v0.19.2)
