### ISSUE TITLE
Please add windows release asset

### ISSUE THREAD

**Issue by W1M0R** [stefanlogue/meteor#39]
Thanks for this tool! 

I'm currently using it on Windows, but have to build it from source since there is no Windows release asset available.

I want to add meteor to Windows package managers like proto and scoop, but it looks like they are built to work with binaries. The aqua package manager can build from source, so I'm using that for now.

@stefanlogue Could you please add a Windows release binary?

I managed to figure out how to [build from source](https://github.com/ScoopInstaller/Scoop/issues/340#issuecomment-2301269015) using Scoop, but having a binary would be simpler.

**Comment by stefanlogue** [comment]
The reason I've not previously added a Windows binary is that I don't have a Windows machine to test it on, but I'd be more than happy to introduce one if you'd be up for testing it out for me?

**Comment by W1M0R** [comment]
@stefanlogue No problem. I use meteor on Windows daily, and would be able to verify it for you.

**Comment by stefanlogue** [comment]
@W1M0R I've tried to release this on scoop, and I'll update the readme soon to reflect this, but in the meantime could you try to install it like this:

```
scoop bucket add <some name> https://github.com/stefanlogue/scoops
scoop install <some name>/meteor
```

If this doesn't work, please let me know as I've very likely messed something up in the scoops repo
