### ISSUE TITLE
LazyGit integration

### ISSUE THREAD

**Issue by Broderick-Westrope** [stefanlogue/meteor#44]
### 🚀 The feature, motivation and pitch

I think it would be great to have a way to integrate this with LazyGit. Perhaps a popup window within LG where the meteor forms are displayed. This would likely require collaboration with the LG team.

### Alternatives

Instead, it could close the LG UI, spawn some kind of sub-process in the normal terminal buffer, and then switch back to the LG UI once meteor is done. I imagine this would be more work, but the LG team may not want to interface with meteor within a window... just guessing :)

### Additional context

This is simply a suggestion; if it doesn't happen then I totally understand. Thanks for building a cool tool!

**Comment by stefanlogue** [comment]
I think an easier way to accomplish this would be to set `meteor` as your default git editor, have a look at #37 as that _should_ work, although I've never actually tested that it works with LazyGit (I don't see why it wouldn't though!).

Please let me know whether it works and any issues you run into, as it would be nice to get this working if it doesn't already
