### ISSUE TITLE
Board ticket # comes back incorrectly if ticket format not in TICKET#: format

### ISSUE THREAD

**Issue by dpuka** [stefanlogue/meteor#46]
### 🐛 Describe the bug

Hello,

I encountered a bug when you change the message format using the messageWithTicketTemplate option.

I set the ticket template format in this syntax:
` "messageWithTicketTemplate": "@type(@scope): @ticket @message",`
So that my commits would look like:
`fix: ADS-123 fixing bug with the thing`

This will work correctly the first commit looks like, however trying to add another commit will instead pull "fix:" as the ticket, instead of my custom location of ADS-123 (in ~middle of the message)

See this example, where my git log has a single commit `feat!: ADS-123 add readme` but meteor will try to grab the "type" part of my prior message, instead prefilling with "ADS"
![image](https://github.com/user-attachments/assets/406b52b4-5cb4-41e3-823f-d127fdaf1631)

 Steps to recreate:
1. Init git repo
2. Add a file
3. meteor and add in format described above.
4. Add new file
5. meteor
6. You will have the incorrect board prefilled in the message

### Versions

v0.24.2

**Comment by stefanlogue** [comment]
@dpuka I've raised a PR which I think will fix this issue, would you mind giving it a test before I merge and release?

**Comment by dpuka** [comment]
@stefanlogue tested and looks good to me! ticket number correctly pulling now
