### ISSUE TITLE
Restricted Scopes

### ISSUE THREAD

**Issue by HarryPeach** [stefanlogue/meteor#48]
### 🚀 The feature, motivation and pitch

If would be nice to specify a list of scopes that the user can pick from, rather than having it entered manually every time (similar to how the prefixes are selected).

### Additional context

We've got some different scopes that are pretty clearly defined in our project but suffer from typos or people having different mental phrasings for the different scopes - i.e. ci/pipeline/pipelines/workflow/actions all meaning essentially the same thing

**Comment by stefanlogue** [comment]
I can see how this could be useful, I'll try to get some time to work on this before the new year

**Comment by stefanlogue** [comment]
@HarryPeach this is now available in the latest release

**Comment by HarryPeach** [comment]
Absolutely fantastic, thanks so much!
